services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/Kernel.php'
            - '../src/Infrastructure/Shared/Persistence/Doctrine/Migrations/'

    # Binding explícito: interfaz de dominio → implementación Doctrine
    App\Domain\Game\Repository\SessionRepositoryInterface:
        class: App\Infrastructure\Game\Persistence\Doctrine\DoctrineSessionRepository
